// ================================================================
// Iceland Economic Analytics — DAX Measures
// Semantic model: gold.* Kimball star schema (Fabric Lakehouse)
// ================================================================
// Percentage indicators are stored as percentage points in the
// fact table (e.g. 9.25 for 9.25%) and divided by 100 here so
// Power BI displays them correctly when formatted as Percentage.
// Index and FX values require no transformation.
// ================================================================


// ── Page 1: Time-Series Measures ─────────────────────────────────

// Central Bank policy rate (end-of-period, % p.a.).
Policy Rate =
DIVIDE(
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "policy_rate"
    ),
    100
)

// Year-on-year CPI inflation rate — pre-computed by the pipeline.
CPI Inflation (YoY) =
DIVIDE(
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "cpi"
    ),
    100
)

// ISK per 1 EUR — a higher value indicates a weaker króna.
ISK/EUR Rate =
CALCULATE(
    AVERAGE('fact_monthly_economics'[value]),
    'dim_indicator'[indicator_code] = "iskeur"
)

// Year-on-year GDP growth rate — pre-computed by the pipeline.
GDP Growth (YoY) =
DIVIDE(
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "gdp_yoy_growth"
    ),
    100
)

// House Price Index (base: March 2000 = 100).
House Price Index =
CALCULATE(
    AVERAGE('fact_monthly_economics'[value]),
    'dim_indicator'[indicator_code] = "hpi"
)

// Wage Index (base: December 1988 = 100).
Wage Index =
CALCULATE(
    AVERAGE('fact_monthly_economics'[value]),
    'dim_indicator'[indicator_code] = "wage_index"
)


// ── KPI Card Measures (latest available month) ────────────────────
// Use these on KPI cards so they show the most recent data point
// rather than the full-period average. LASTNONBLANK returns the last
// date that has a non-blank value for the given indicator.

Policy Rate (Latest) =
VAR _lastKey =
    CALCULATE(
        MAX('fact_monthly_economics'[date_key]),
        'dim_indicator'[indicator_code] = "policy_rate"
    )
RETURN
DIVIDE(
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "policy_rate",
        'fact_monthly_economics'[date_key] = _lastKey
    ),
    100
)

CPI Inflation (Latest) =
VAR _lastKey =
    CALCULATE(
        MAX('fact_monthly_economics'[date_key]),
        'dim_indicator'[indicator_code] = "cpi"
    )
RETURN
DIVIDE(
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "cpi",
        'fact_monthly_economics'[date_key] = _lastKey
    ),
    100
)

ISK/EUR Rate (Latest) =
VAR _lastKey =
    CALCULATE(
        MAX('fact_monthly_economics'[date_key]),
        'dim_indicator'[indicator_code] = "iskeur"
    )
RETURN
CALCULATE(
    AVERAGE('fact_monthly_economics'[value]),
    'dim_indicator'[indicator_code] = "iskeur",
    'fact_monthly_economics'[date_key] = _lastKey
)

GDP Growth (Latest) =
VAR _lastKey =
    CALCULATE(
        MAX('fact_monthly_economics'[date_key]),
        'dim_indicator'[indicator_code] = "gdp_yoy_growth"
    )
RETURN
DIVIDE(
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "gdp_yoy_growth",
        'fact_monthly_economics'[date_key] = _lastKey
    ),
    100
)

House Price Index (Latest) =
VAR _lastKey =
    CALCULATE(
        MAX('fact_monthly_economics'[date_key]),
        'dim_indicator'[indicator_code] = "hpi"
    )
RETURN
CALCULATE(
    AVERAGE('fact_monthly_economics'[value]),
    'dim_indicator'[indicator_code] = "hpi",
    'fact_monthly_economics'[date_key] = _lastKey
)

Wage Index (Latest) =
VAR _lastKey =
    CALCULATE(
        MAX('fact_monthly_economics'[date_key]),
        'dim_indicator'[indicator_code] = "wage_index"
    )
RETURN
CALCULATE(
    AVERAGE('fact_monthly_economics'[value]),
    'dim_indicator'[indicator_code] = "wage_index",
    'fact_monthly_economics'[date_key] = _lastKey
)


// ── Page 2: Crisis Comparison Measures ───────────────────────────
// Intended for a matrix with dim_date[crisis_period] as columns.
// Apply a visual-level filter to exclude "Normal" — leaving the
// three crisis columns: Banking Collapse, Pandemic, Inflation & Volcanic.

// Highest CPI inflation recorded within the filtered crisis period.
Peak CPI =
DIVIDE(
    CALCULATE(
        MAX('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "cpi"
    ),
    100
)

// Highest policy rate recorded within the filtered crisis period.
Peak Policy Rate =
DIVIDE(
    CALCULATE(
        MAX('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "policy_rate"
    ),
    100
)

// Lowest (worst) quarterly GDP growth recorded within the filtered crisis period.
// Uses MIN over quarterly observations — differs from the annual-average bars on page 1.
Worst GDP Growth =
DIVIDE(
    CALCULATE(
        MIN('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "gdp_yoy_growth"
    ),
    100
)

// Highest ISK/EUR rate recorded within the filtered crisis period.
Peak ISK/EUR =
CALCULATE(
    MAX('fact_monthly_economics'[value]),
    'dim_indicator'[indicator_code] = "iskeur"
)

// HPI divided by Wage Index — a rising ratio means housing costs
// are outpacing wages (lower = more affordable).
Affordability Ratio =
DIVIDE(
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "hpi"
    ),
    CALCULATE(
        AVERAGE('fact_monthly_economics'[value]),
        'dim_indicator'[indicator_code] = "wage_index"
    )
)
